### PR TITLE
Add login feature

### PR DESCRIPTION
**Pull request by rjbelleza**
Created User Interface for the Login Page of the app. Created a component that will show a paginated list of users, along with their credentials. Installed several dependencies and libraries for the functionality and interface of the entire application.

### CODE REVIEW

**Review by backup-droid — APPROVED** [review]
Merge ready...

**Comment by Chen100404** [comment]
The designs and the code are already good enough for me.

**Comment by philipelbambo** [comment]
the code is will be perfect

**Review by backup-droid — APPROVED** [review]

**Comment by Skenkenken** [comment]
Everything seems to be in order

**Pull request merged**
